#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021 jerryk <jerrykuku@qq.com>
#
# This is free software, licensed under the APACHE LICENSE, VERSION 2.0.
# See /LICENSE for more information.
#
USE_PROCD=1

START=99
STOP=15

NAME=go-aliyundrive-webdav

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

start_service() {
  local enable=$(uci_get_by_type server enable)
  case "$enable" in
    1|on|true|yes|enabled)
      local refresh_token=$(uci_get_by_type server refresh_token)
      local auth_user=$(uci_get_by_type server auth_user admin)
      local auth_pwd=$(uci_get_by_type server auth_pwd 123456)
      local port=$(uci_get_by_type server port 8085)

      procd_open_instance
      procd_set_param command /bin/sh -c "/usr/bin/$NAME -rt $refresh_token --port $port --user $auth_user --pwd $auth_pwd >>/var/log/$NAME.log 2>&1"
      procd_set_param pidfile /var/run/$NAME.pid
      procd_close_instance ;;
    *)
      stop_service ;;
  esac
}

service_triggers() {
	procd_add_reload_trigger "/etc/config/$NAME"
}
